version: "3.8"

services:
  recetas-db:
    image: mysql
    networks:
      - spring-web
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dados
      - MYSQL_DATABASE=dados
      - MYSQL_USER=dados
      - MYSQL_PASSWORD=dados
networks:
  spring-web: